name = "wild-firefly-cbaa"
main = "src/index.js"
compatibility_date = "2022-06-17"

[vars]
hcapt_sitekey = "bc1cef70-1228-40cf-abb3-537dbed749c0"
hcapt_sitesecret = "0x1254492dC3aadD85C4D112B8641eeDf59D8B63f6"
urlPrefix = "OHFavwo5zDK8VGIN"
envVar_jwkKey = "u5agEMLRPuoP0qaMGP4Jw6FhkiKctDfMZilnTf2J7vI"
envVar_jwkUUID = "6b773fdb-49ce-49e9-bda9-dfe0e1258084"